sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product dmtn-116
env:
  global:
    # LSST the Docs credentials
    - secure: "AQXS3+AogLVvc9a3YvtYZ0SKamJvs76VoGJR1BPROhHEd/4MWCnBUi0CKHzhxvHbbIsqP9nqpy1PXsDA3gtufZf5VjrSV+LbjiQl2NTIUo6NEWsTNtebWEHD1SejRWPavXSh2f8igw3BNxqQE9o8nUPwi/o0ldhclyVyv2Y0v0fQXYFyeyg6g0ZKWQzRUea3DF14/kfSTNTXry7Jazvh1LTJhPGWq/lwsdnk4yblj82j4Ret3eCDjVXpt3HGhW42ayG+nvXTJVmplPqJ/6qIsvDQcQkyOirWfNQoVPRIYPiTvD8NcostDDJSCnuVbFgKjZW7qE0FrA8w9WmcCk1GDHyEZr3iODeU5CuQ5USy4IW8/CpUirnEyZn9ln1yzfx4MiDsAAYqeA9di+1gnQVtVtU/Z4leNn9tT3qNt1HtXWlAEeCWIaVDSAv0qaGC9OZBDBxQgEcUKhZ/Yqizdw8SXEcJrxLxYvAX9Ndg4++Lt/rclp79jHBGiGxI+fmEsGjQMjhwfEKqqSVWpjpvBIGe8fe9DlYSAOTPvKQPqsp1Hov0r02ZfMl7eyolBo3PS51ghxes/VsWi3L9pR/IS4JmEVb0slDXZtVnHeT0gEecSekP1yl2tr+1BnG5YzcwzNNtGiMxbSPzHj+rJSL4bt7fW7v3uoFFxExcdJGt7nFJSB0="
    - secure: "nY82MGJhBPV5Dk/uPRHwpf8XvmtUkjd4XG0EV5oyDWOaK9k7K5J2jTN3JEL8a62qXKQgvoj7v/GJ83vtaI07RT+IBp5S66S3gXYdZ845Vicmfq+DgNXq1CWcpAo3x6e/Vhi35R7LS+BhqGoPB1T0aSKklOuDfB9IsE2cvRNu8nPSlyuydccbFwrKDHxADIX9/8si82EKFveqPiw1v0y9dMGlVlj6T4yZQoV92MGs88qVNM4rsmHOU21uZ2KTs12xKsRogIQ1ktOSRcuwdaDz4nJBCCxr7WsDRGODMhPenpi1qefEb6wu8zLWTDUYzxnnrp9bxr3FzO1EOrVLB8BF9fdx/pT8c9jCREgh1qv2+a16D2XdQGDsD4U4fCadFaQDkxyJC1j9BVmelKGNR7/f8g/35b8n6VqvSnmVKNL/ApT/R2AkAIi1dbZgj1U8IRull8OEmybz5ZQ/8OQqlSSOpL0cV4qutcJoOlhcmVXkm0R14JbjziKvhdwdJ9ULXXbkk7ezywXysnKdMK8cxYQrOV2DBVoXwU7sju8NOPUNgzQ4AJxGUooqu9rx0mO/NbkbO/4s4jm9jcA0p7YhNLt7LTYE0Dk2d9CpbUloOFMeqkaIEEBRC8eDdnJXhOnjfy75XNloB/dorF6gqSkmaD43CmnQ7aMwbPzyrmIfT0Fs6Zs="
